events {
        # The maximum number of simultaneous connections that can be opened by
        # a worker process.
        worker_connections 1024;
}

http {
    upstream superset_backend {
        server superset:8088;
        server superset:8088;
        server superset:8088;
        server superset:8088;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://superset_backend;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
            #include proxy_params;
            #proxy_connect_timeout 60s;
            #proxy_read_timeout 5400s;
            #proxy_send_timeout 5400s;
            #proxy_redirect default;

	    # Handle redirects if necessary
            proxy_redirect http://superset_backend/ /;

        }
    }
}

