name: pre-commit checks

on:
  push:
    branches:
<<<<<<< HEAD
      - "master"
      - "[0-9].[0-9]*"
=======
      - 'master'
>>>>>>> 2d98af4662 (merge from upstream to master)
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

# cancel previous workflow jobs for PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
<<<<<<< HEAD
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["current", "next", "previous"]
=======
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.9"]
>>>>>>> 2d98af4662 (merge from upstream to master)
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Python
<<<<<<< HEAD
        uses: ./.github/actions/setup-backend/
        with:
          python-version: ${{ matrix.python-version }}
      - name: Enable brew and helm-docs
        # Add brew to the path - see https://github.com/actions/runner-images/issues/6283
=======
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements/base.txt
            requirements/integration.txt
      - name: Install dependencies
        uses: ./.github/actions/cached-dependencies
        with:
          run: |
            apt-get-install
            pip-upgrade
            pip install wheel
            pip install -r requirements/base.txt
            pip install -r requirements/integration.txt
      # Add brew to the path - see https://github.com/actions/runner-images/issues/6283
      - name: Enable brew and helm-docs
>>>>>>> 2d98af4662 (merge from upstream to master)
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "HOMEBREW_PREFIX=$HOMEBREW_PREFIX" >>"${GITHUB_ENV}"
          echo "HOMEBREW_CELLAR=$HOMEBREW_CELLAR" >>"${GITHUB_ENV}"
          echo "HOMEBREW_REPOSITORY=$HOMEBREW_REPOSITORY" >>"${GITHUB_ENV}"
          brew install norwoodj/tap/helm-docs
      - name: pre-commit
        run: |
<<<<<<< HEAD
          set +e  # Don't exit immediately on failure
          pre-commit run --all-files
          if [ $? -ne 0 ] || ! git diff --quiet --exit-code; then
            echo "❌ Pre-commit check failed."
            echo "🚒 To prevent/address this CI issue, please install/use pre-commit locally."
            echo "📖 More details here: https://superset.apache.org/docs/contributing/development#git-hooks"
=======
          if ! pre-commit run --all-files; then
            git status
            git diff
>>>>>>> 2d98af4662 (merge from upstream to master)
            exit 1
          fi
